// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvGM3yT-SQ3gjErPis5VVSAK2XkFdvKs',
    appId: '1:1014745690021:web:047820bba9ff4f7949c24c',
    messagingSenderId: '1014745690021',
    projectId: 'gwcl-752e8',
    authDomain: 'gwcl-752e8.firebaseapp.com',
    storageBucket: 'gwcl-752e8.appspot.com',
    measurementId: 'G-RSB370318E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnMTwAUpnNSE16vLpq3ixmJ9Tccya9fc',
    appId: '1:1014745690021:android:e5fd7fe3a547dbd949c24c',
    messagingSenderId: '1014745690021',
    projectId: 'gwcl-752e8',
    storageBucket: 'gwcl-752e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQeBsmTfJzpnb4c81b8bmGY7YHHLG-fsw',
    appId: '1:1014745690021:ios:9e542671c7b8f60c49c24c',
    messagingSenderId: '1014745690021',
    projectId: 'gwcl-752e8',
    storageBucket: 'gwcl-752e8.appspot.com',
    iosClientId: '1014745690021-14quhi39g2h64iqcijitmrrcf863g0n8.apps.googleusercontent.com',
    iosBundleId: 'com.afrifanom.gwcl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQeBsmTfJzpnb4c81b8bmGY7YHHLG-fsw',
    appId: '1:1014745690021:ios:9e542671c7b8f60c49c24c',
    messagingSenderId: '1014745690021',
    projectId: 'gwcl-752e8',
    storageBucket: 'gwcl-752e8.appspot.com',
    iosClientId: '1014745690021-14quhi39g2h64iqcijitmrrcf863g0n8.apps.googleusercontent.com',
    iosBundleId: 'com.afrifanom.gwcl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbvGM3yT-SQ3gjErPis5VVSAK2XkFdvKs',
    appId: '1:1014745690021:web:abb8f4b13f33578049c24c',
    messagingSenderId: '1014745690021',
    projectId: 'gwcl-752e8',
    authDomain: 'gwcl-752e8.firebaseapp.com',
    storageBucket: 'gwcl-752e8.appspot.com',
    measurementId: 'G-B4CR82KL1Q',
  );
}
